#!/usr/bin/env python3
"""
NXC Module: generate_hosts
Creates a hosts file from SMB scan results with IP-to-hostname mappings.
"""

from datetime import datetime
from pathlib import Path


class NXCModule:
    """
    Generates a hosts file from SMB scanning results.
    Captures IP addresses and hostnames discovered during authentication.
    """

    name = "generate_hosts"
    description = "Creates a hosts file from SMB scan results"
    supported_protocols = ["smb"]
    opsec_safe = True
    multiple_hosts = True

    def __init__(self):
        self.hosts = {}

    def options(self, context, module_options):
        """
        Module options:
            OUTPUT      Path to output hosts file (default: ./hosts_nxc.txt)
            APPEND      Append to existing file instead of overwriting (default: False)
            DOMAIN      Include domain suffix in hostnames (default: False)
        """
        self.output_file = module_options.get("OUTPUT", "./hosts_nxc.txt")
        self.append_mode = module_options.get("APPEND", "False").lower() == "true"
        self.include_domain = module_options.get("DOMAIN", "False").lower() == "true"

    def on_login(self, context, connection):
        """Captures host information after successful SMB connection."""
        try:
            ip = connection.host
            hostname = connection.hostname
            domain = connection.domain

            if ip and hostname:
                # Build the hostname entry
                if self.include_domain and domain and domain != hostname:
                    # Include both FQDN and short name
                    fqdn = f"{hostname}.{domain}".lower()
                    host_entry = f"{fqdn} {hostname.lower()}"
                else:
                    host_entry = hostname.lower()

                self.hosts[ip] = host_entry

                context.log.success(f"Captured: {ip} -> {host_entry}")

                # Write to file after each host (in case scan is interrupted)
                self._write_hosts_file(context)

            else:
                context.log.fail(f"Could not resolve hostname for {ip}")

        except Exception as e:
            context.log.fail(f"Error capturing host info: {e}")

    def _write_hosts_file(self, context):
        """Writes the collected hosts to the output file."""
        try:
            output_path = Path(self.output_file).expanduser().resolve()

            # Read existing entries if appending
            existing_hosts = {}
            if self.append_mode and output_path.exists():
                with open(output_path, "r") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#"):
                            parts = line.split(None, 1)
                            if len(parts) >= 2:
                                existing_hosts[parts[0]] = parts[1]

            # Merge with new hosts (new entries override existing)
            all_hosts = {**existing_hosts, **self.hosts}

            # Write the hosts file
            with open(output_path, "w") as f:
                f.write(f"# Generated by nxc generate_hosts module\n")
                f.write(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"# Total hosts: {len(all_hosts)}\n")
                f.write("#" + "=" * 50 + "\n\n")

                # Sort by IP for readability
                for ip in sorted(all_hosts.keys(), key=lambda x: tuple(map(int, x.split(".")))):
                    f.write(f"{ip}\t{all_hosts[ip]}\n")

            context.log.debug(f"Hosts file updated: {output_path}")

        except Exception as e:
            context.log.fail(f"Error writing hosts file: {e}")

    def on_shutdown(self, context, connection):
        """Final summary when module completes."""
        if self.hosts:
            context.log.highlight(f"Total hosts captured: {len(self.hosts)}")
            context.log.highlight(f"Hosts file: {Path(self.output_file).resolve()}")
